[80] Implement actor apply jobs API @POST
2110336-2565-2/sec2-group9-modela pull request #100
Opened 2023-02-25 15:46 UTC by palmcm

## What did you do

-add endpoint for applyJob

## Demo

- login as actor 
- check exist resume or create new one
- try to test apply job

2023-02-25 17:04 UTC, miello requested changes

2023-02-25 17:04 UTC, miello commented on apps/api/src/modules/job/application/application.service.spec.ts
> +      ).resolves.toEqual({ applicationId: MOCK_APPLICATION.applicationId })
```suggestion
      await expect(
        service.applyJob(MOCK_JOB_ID, MOCK_RESUME.resumeId, MOCK_ACTORS_ID),
      ).resolves.toEqual({ applicationId: MOCK_APPLICATION.applicationId })
```

2023-02-25 17:04 UTC, miello commented on apps/api/src/modules/job/application/application.service.spec.ts
> +      ).resolves.toEqual({ applicationId: MOCK_APPLICATION.applicationId })
Please add `await` for all resolves or rejects checking

2023-02-25 17:04 UTC, miello commented on apps/api/src/modules/job/application/application.controller.ts
> +  }
Where is success response in swagger details ?

2023-02-26 08:35 UTC, palmcm commented
@miello pls review ;w;

2023-02-26 08:37 UTC, miello approved these changes
I'm sincerely apologize for late review

2023-02-26 08:38 UTC, merged