[79] Implement actor apply jobs UI
2110336-2565-2/sec2-group9-modela pull request #112
Opened 2023-02-28 15:59 UTC by fainrada

## What did you do

![image](https://user-images.githubusercontent.com/73642776/221900116-09e51df3-6dc3-4302-b95e-84185b302b9c.png)
- Add actor apply page, actor is able to apply job by choosing a resume with dropdown
- link apply button in JobCardFooter to actor apply page
- Add jobId as number type in FooterProps type.ts
 
## Demo

- https://dev.modela.miello.dev/job
- Login with actor
- Choose a job to apply
- Choose resume and click "apply"
- If you already apply to this job, an error snackbar will popup with text "คุณได้สมัครงานนี้ไปแล้ว"
- Else, a success snack bar will popup with text "การสมัครเสร็จสิ้น" and post data to backend

## Limitation

- no unit test

2023-02-28 16:23 UTC, PKhing requested changes

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/components/SelectResume/index.tsx
> +  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
you can use `const {id, setId, resumes} = props` 
then use `props.setId(Number(event.target.value))` `value = {id}` and `resumes.map`
for cleaner code

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/components/SelectResume/index.tsx
> +import * as React from 'react'
```suggestion
import React from 'react'
```

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/components/SelectResume/index.tsx
> +          ))}
same as above
```suggestion
          {resumes.map(({resumeId, name}: ResumeDto) => (
            <MenuItem key={resumeId} value={resumeId}>
              {name}
            </MenuItem>
          ))}
```

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/components/SelectResume/types.ts
> +  Id: number | undefined
```suggestion
  id: number | undefined
```

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +  const [Id, setId] = React.useState<number | undefined>()
```suggestion
  const [id, setId] = React.useState<number | undefined>()
```

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +      const resumeIdBody: ResumeIdDto = {
resumeId should be checked before POST to backend (we should not send bad request data)

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/apply/pages/index.tsx
> +  if (loading) return <CircularProgress />
My bad I think that this is loading for fetching data, but actually, it is loading for submitting data.
We should move Circular progress to the submit button (see example in `modules/login/index.tsx`)

2023-02-28 16:23 UTC, PKhing commented on apps/web/src/modules/job/list/components/JobCardContainer/components/JobCard/index.tsx
> +          jobId={prop.jobId}
```suggestion
          jobId={jobId}
```

2023-02-28 16:38 UTC, miello requested changes

2023-02-28 16:38 UTC, miello commented on apps/web/src/modules/job/apply/components/SelectResume/types.ts
> +  setId: (Id: number) => void
```suggestion
  setId: (id: number) => void
```

2023-02-28 16:38 UTC, miello commented on apps/web/src/modules/job/apply/pages/index.tsx
> +        <SelectResume resumes={resumes} Id={Id} setId={setId}></SelectResume>
This should fix along with `Id`
```suggestion
        <SelectResume resumes={resumes} id={id} setId={setId}></SelectResume>
```

2023-03-01 05:56 UTC, miello requested changes

2023-03-01 05:56 UTC, miello commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +import { useCallback, useEffect, useState } from 'react'
```suggestion
import { useCallback, useEffect, useState } from 'react'
```

2023-03-01 05:56 UTC, miello commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +  const [id, setId] = React.useState<number | undefined>()
```suggestion
  const [id, setId] = useState<number | undefined>()
```

2023-03-01 05:56 UTC, miello commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +      }
(Discussion)
Should we change handle missing resumeId from `displaySnackbar` to assign message to `helperText` in TextField instead ?

2023-03-01 05:56 UTC, miello commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +      }
Please see other page such as login, register for reference

2023-03-01 05:56 UTC, miello commented on apps/web/src/modules/job/apply/pages/hooks/index.ts
> +  const [resumes, setResumes] = React.useState<ResumeDto[]>([])
```suggestion
  const [resumes, setResumes] = useState<ResumeDto[]>([])
```

2023-03-01 06:51 UTC, PKhing approved these changes

2023-03-01 14:27 UTC, miello approved these changes

2023-03-01 14:28 UTC, merged