[77] add feature in change job's status API @PUT
2110336-2565-2/sec2-group9-modela pull request #116
Opened 2023-03-12 08:34 UTC by SuitedIceZ

## What did you do
- endpoint ```GET /profiles/:id``` add a feature that the same role can't view each other
- endpoint ```PUT /jobs/:id/status```
- add ForbiddenException when change JobStatus is not in order
- change ApplicationStatus of application in the job when changing JobStatus
![image](https://user-images.githubusercontent.com/48400275/224528738-1722f9e6-88dc-46f6-817b-30a087fbe50b.png)

## Demo
- https://dev.modela.miello.dev/
- login with any casting in one window
- login with actor that has resumes (maybe 1,2) in another window
- as casting create new job
- as actor apply that created job
- as casting change that JobStatus in order until "เสร็จสิ้นการคัดเลือก" (SELECTION_END)
- any pending actors will automatically change ApplicationStatus to "ไม่ผ่านการคัดเลือก" (REJECTED)

## Limitation
- not have unit test yet

2023-03-12 09:48 UTC, miello requested changes

2023-03-12 09:48 UTC, miello commented on apps/api/src/modules/user/profile/profile.service.ts
> +    const TargetUser = await this.repository.getUserProfileById(id)
```suggestion
    const targetUser = await this.repository.getUserProfileById(id)
```

2023-03-12 09:48 UTC, miello commented on apps/api/src/modules/user/profile/profile.service.ts
> +    }
```suggestion
    if (user.userId !== id && user.type === TargetUser.type) {
        // user can't see other user's profile if they are the same type
        throw new ForbiddenException()
    }
```

2023-03-12 09:48 UTC, miello commented on apps/api/src/modules/job/job.service.ts
> +    )
```suggestion
    if (
      this.JobStatusToNumber(job.status) + 1 !==
        this.JobStatusToNumber(updateJobStatus) &&
      updateJobStatus !== JobStatus.CANCELLED
    )
```

2023-03-13 12:49 UTC, miello reviewed
LGTM, please wait for review from @palmcm

2023-03-13 14:22 UTC, palmcm approved these changes
LGTM

2023-03-13 15:08 UTC, miello approved these changes

2023-03-13 15:09 UTC, merged