[92][95][98][104][107][110] Implement account page and CastingRejectedForm
2110336-2565-2/sec2-group9-modela pull request #117
Opened 2023-03-13 06:56 UTC by CDGstudent

## What did you do

- add PendingUserPage, PendingUserCard, UserConfirmationCard, UserRejectionCard, usePendingUserData, RejectedForm for Casting

## Demo

-

2023-03-13 13:59 UTC, PKhing commented
- padding
![image](https://user-images.githubusercontent.com/19553305/224722077-b8697302-1222-45b9-b8da-818bb695c06b.png)
![image](https://user-images.githubusercontent.com/19553305/224722642-1bf62399-a96d-4520-8156-52678d040896.png)
- space between cards is too wide

2023-03-13 14:01 UTC, PKhing commented
- border radius again
- reason should be multiple lines (see description field in edit profile page for an example)
![image](https://user-images.githubusercontent.com/19553305/224724360-fb6f0673-c672-4beb-8282-88b0462ad507.png)

2023-03-13 14:02 UTC, PKhing commented
responsive
![image](https://user-images.githubusercontent.com/19553305/224724638-97cce25e-56e4-40f6-bfc4-22db78627893.png)

2023-03-13 15:05 UTC, PKhing requested changes
Currently the structure is
```
Component
  Body
    index << the main component is exported from this file
  Footer
    index
  Header
    index
```

but it should be
```
Component
  Body
    index
  Footer
    index
  Header
    index
index << the main component is exported from this file
```

2023-03-13 15:05 UTC, PKhing commented on apps/web/src/modules/account/pages/index.tsx
> +  const pendingUserData = usePendingUserData()
```suggestion
  const {pendingUserData ,setModalReason บลา ๆ } = usePendingUserData()
```

2023-03-13 15:05 UTC, PKhing commented on apps/web/src/modules/account/pages/index.tsx
> +            />
add key here (please read this https://www.geeksforgeeks.org/reactjs-keys/)

2023-03-13 15:05 UTC, PKhing commented on apps/web/src/modules/rejected/casting/type.ts
> +  initialData: any
P'Yu mai took jai sing nee (type any is not acceptable here)

2023-03-13 15:17 UTC, miello requested changes

2023-03-13 15:17 UTC, miello commented on apps/web/src/modules/account/component/PendingUserCard/Body/index.tsx
> +      <>
Fragment is not necessary in this case, please consider remove

2023-03-13 18:21 UTC, PKhing commented
components
![image](https://user-images.githubusercontent.com/19553305/224794182-8ccae1a2-4aff-4949-a84b-2fb903f42b0a.png)

2023-03-14 01:57 UTC, PKhing requested changes

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardFooter/index.tsx
> +  const [openAccept, setOpenAccept] = React.useState(false)
use useSwitch (read from change log)

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardFooter/index.tsx
> +  const [openReject, setOpenReject] = React.useState(false)
same as above

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardFooter/index.tsx
> +  }
useCallback (for all function in this page)

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardFooter/index.tsx
> +        aria-describedby="modal-modal-description"
is this necessary ?

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardFooter/index.tsx
> +        aria-describedby="modal-modal-description"
is this necessary ?

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/PendingUserCardHeader/index.tsx
> +          {props.type === 'CASTING' && (
enum

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/PendingUserCard/index.tsx
> +      )}
```suggestion
      {type === UserType.CASTING ? (
        <Typography variant="subtitle2" color="#00000099">
          เลขจดทะเบียน: {companyId}
        </Typography>
      ) : (
        <Typography variant="subtitle2" color="#00000099">
          เลขบัตรประจำตัวประชาชน/เลขพาสปอร์ต: {ssn}
        </Typography>
      )}
```

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/UserConfirmationModal/UserConfirmationModalHeader/index.tsx
> +export default UserConfirmationModalHeader
เอาไปรวมกับ index

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/component/UserRejectionModal/UserRejectionModalHeader/index.tsx
> +export default UserRejectionModalHeader
รวมกับ index

2023-03-14 01:57 UTC, PKhing commented on apps/web/src/modules/account/hooks/usePendingUserData/index.ts
> +          rejectedReason: '',
remove reason

2023-03-14 01:58 UTC, miello requested changes

2023-03-14 01:58 UTC, miello commented on apps/web/src/modules/account/component/PendingUserCard/index.tsx
> +import { UserType } from '@modela/database'
```suggestion
import { UserType } from '@modela/dtos'
```

2023-03-14 01:58 UTC, miello commented on apps/web/src/modules/account/pages/index.tsx
> +  } = usePendingUserData()
```suggestion
  const {
    pendingUserData,
    ...functionCard
  } = usePendingUserData()
```

2023-03-14 01:58 UTC, miello commented on apps/web/src/modules/account/pages/index.tsx
> +            />
```suggestion
            <PendingUserCard
              key={user.data.userId}
              data={user}
              {...functionCard}
            />
```

2023-03-14 01:58 UTC, miello commented on apps/web/src/modules/rejected/pages/index.tsx
> +import { ActorInfoDto, CastingInfoDto } from '@modela/dtos'
```suggestion
import { ActorInfoDto, CastingInfoDto, UserType } from '@modela/dtos'
```

2023-03-14 02:03 UTC, PKhing commented
ทำตัวหนา (วิธีมีเขียนไว้ใน change log แล้ว)
![image](https://user-images.githubusercontent.com/19553305/224873227-f2d2b1be-6af7-4d2e-ba72-766e7235f772.png)

2023-03-14 02:04 UTC, PKhing commented
bottom padding ยังไม่มีเลยครับ
![image](https://user-images.githubusercontent.com/19553305/224873424-657a460e-afcd-4f37-98d9-8650d48000d0.png)

2023-03-14 02:05 UTC, PKhing commented
card แคบไปป่ะนะ (width ~930 px)
![image](https://user-images.githubusercontent.com/19553305/224873593-a7d1fdcb-a459-4178-9a6f-1f22ebe2ca05.png)

2023-03-14 02:07 UTC, PKhing commented
top and bottom space is not balance
![image](https://user-images.githubusercontent.com/19553305/224873732-cdb826da-fa3b-446c-89e1-6ae0764c9104.png)
![image](https://user-images.githubusercontent.com/19553305/224873785-ac8eeb05-9294-450e-9e28-6370940a3a87.png)

2023-03-14 02:07 UTC, PKhing commented
iphone XR
![image](https://user-images.githubusercontent.com/19553305/224873900-24f0b6c9-ce5b-412b-8f5e-19173d08d086.png)

2023-03-21 05:59 UTC, PKhing approved these changes

2023-03-21 08:29 UTC, merged