[176] [180] [76]
2110336-2565-2/sec2-group9-modela pull request #149
Opened 2023-03-28 17:02 UTC by priasdevo

## What did you do

- Fix responsive for JobMenu ( 76 sprint 2 task)
- ![image](https://user-images.githubusercontent.com/73303542/228314295-ef8d30d4-4399-42bf-ba2d-1b23b827a415.png)
- Implement Notification Page for Actor/Casting
- ![image](https://user-images.githubusercontent.com/73303542/228314437-5a21f357-bed2-405d-9849-e79190ce7ab9.png)
- Accept/Reject offer from notification Page

## Demo

- http://localhost:3000/notification

2023-03-28 17:43 UTC, miello requested changes
This covers only code reviews

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/job/components/JobMenu/styled.ts
> +`
```suggestion
export const StatusButton = styled(Button)`
  border-radius: 12px;
  width: 100%;
  font-size: 16px;
  ${(props) => props.theme.breakpoints.down('lg')} {
    width: 50%;
    margin: 10px 30px 0 30px;
  }
`
```

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardBody/index.tsx
> +          <Link href={'/job/' + jobId} underline="none">
```suggestion
          <Link href={`/job/${jobId}`} underline="none">
```

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardBody/index.tsx
> +          <Link href={'/profile/' + actorId} underline="none">
```suggestion
          <Link href={`/profile/${actorId}`} underline="none">
```

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardFooter/index.tsx
> +            }}
Consider making it another function

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardFooter/index.tsx
> +              openAcceptModal()
Consider making it another function

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/NoticardContainer/components/NotiCard/Components/NotiCardHeader/index.tsx
> +              type === NotificationType.REJECT_REFUND)
Repetitive condition checking to line 46, maybe making it as an another variable ?

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/pages/index.tsx
> +      console.log('TEST')
???

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/components/RejectOfferModal/styled.ts
> +`
Consider using `color="success"` or `color="error"` instead

2023-03-28 17:43 UTC, miello commented on apps/web/src/modules/notification/pages/hooks/useModalData/index.ts
> +      await apiClient.put<string>(`/jobs/` + focusId + '/offer/reject')
```suggestion
      await apiClient.put<string>(`/jobs/${focusId}/offer/reject`)
```

2023-03-29 13:37 UTC, miello commented
Too much width ? (Account casting 10 and jobId 1)
![image](https://user-images.githubusercontent.com/35169079/228555604-ec3705cb-9bc4-429a-b117-9fb360ff8e75.png)

2023-03-29 13:37 UTC, miello commented
![image](https://user-images.githubusercontent.com/35169079/228555868-9a67b691-75fb-4469-8a21-cc3e7362f46e.png)

Maybe wrap to new line ?

2023-03-30 05:09 UTC, priasdevo commented
@miello

2023-03-30 08:23 UTC, miello approved these changes

2023-03-30 08:25 UTC, merged