[161] Implement Admin pending refund page
2110336-2565-2/sec2-group9-modela pull request #154
Opened 2023-03-29 16:30 UTC by miello

## What did you do

- Implement admin pending refund page
- Implement refund page action (accept, reject)

## Demo

- Login as any admin account
- Go to https://dev.modela.miello.dev/transaction/refund

![image](https://user-images.githubusercontent.com/35169079/228606145-d9df574a-5f33-4ea5-b487-11dcd1dd3cd1.png)

![image](https://user-images.githubusercontent.com/35169079/228606213-cadb6540-1fa4-4256-85a9-2a8d90a9aad2.png)

2023-03-30 14:22 UTC, pisuttun requested changes
Other than this, trust in miello

2023-03-30 14:22 UTC, pisuttun commented on apps/web/src/modules/transaction/pages/refund/components/PendingRefundCard/index.tsx
> +import { JobStatus } from '@modela/database'
```suggestion
import { JobStatus } from '@modela/dtos'
```
:cat_smile:

2023-03-30 15:06 UTC, PKhing commented
ฝากแก้ guard ในหน้า /profile หน่อย ตอนนี้ admin เข้าไม่ได้ กดชื่อแล้ววาร์ปไปหน้าแรกเฉย 
![image](https://user-images.githubusercontent.com/19553305/228880671-d21d1a5a-d5bd-4f78-ac8b-2608686648ed.png)

2023-03-30 15:38 UTC, pisuttun approved these changes

2023-03-31 01:32 UTC, PKhing approved these changes

2023-03-31 01:43 UTC, merged