[28] Implement post a jobs API @POST
2110336-2565-2/sec2-group9-modela pull request #37
Opened 2023-02-09 11:01 UTC by badnameok

## What did you do

- Implemented post jobs API
- Currently the job status will default to OPEN.
- Also includes a simple test unit.

## Demo

- Swagger -> Post /job

2023-02-09 11:09 UTC, badnameok commented
มันบอกว่าไม่เจอ IsDateString แต่ใน branch เรามัน import ไว้แล้วหนิ :/

2023-02-09 11:13 UTC, PKhing commented
where is all validation? ex. min age must <= max age , start time <= end time

2023-02-09 12:00 UTC, PKhing commented
มี validation อื่นอีกครับ ไม่ได้มีแค่ที่พิมพ์บอกไปข้างบน

2023-02-09 12:14 UTC, palmcm requested changes
There will be more

2023-02-09 12:14 UTC, palmcm commented on apps/api/src/modules/job/job.service.ts
> +      return
```suggestion
      throw new BadRequestException('minAge is greater than maxAge')
```
If throw don't have to return and this is bad request error not forbidden

2023-02-09 12:14 UTC, palmcm commented on apps/api/src/modules/job/job.service.ts
> +    }
Should do something with e(error) like console.log(e). If not there is no need to try catch

2023-02-09 12:14 UTC, palmcm commented on packages/dtos/src/job.ts
>    maxAge: number
Add decorator for this too

2023-02-09 12:14 UTC, palmcm commented on apps/api/src/modules/job/job.service.ts
> +      await this.repository.createJob(createJobDto, userId)
Should return created jobid

2023-02-09 12:36 UTC, PKhing requested changes

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.controller.ts
> +  @UseTypeAuthGuard('CASTING')
```suggestion
  @UseTypeAuthGuard(UserType.CASTING)
```

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.repository.ts
> +    const job = await this.prisma.job.create({
![image](https://user-images.githubusercontent.com/19553305/217812992-11beb51b-b5af-4f4a-ae2f-1ca18159c766.png)

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.repository.ts
> +      },
```suggestion
     data: {
        status: JobStatus.OPEN,
        castingId: userId,
        ...rest,
        Shooting: {
          create: shooting,
        },
      },
```

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.service.spec.ts
> +    const MOCK_SHOOTING = mock('shooting').get(3)
![image](https://user-images.githubusercontent.com/19553305/217813524-d253b068-9089-4c23-b61a-01822757529a.png)

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.service.spec.ts
> +        jest.spyOn(service, 'createJob').mockResolvedValue()
Why did you mock return service? If you mock return that how can you test whether the return value is correct or not?

2023-02-09 12:36 UTC, PKhing commented on apps/api/src/modules/job/job.service.spec.ts
> +        expect(service.createJob).toBeCalledWith(MOCK_JOB, MOCK_CASTING_ID)
You called `service.createJob` 3 lines above. What do you want to test here?

2023-02-09 13:35 UTC, miello requested changes

2023-02-09 13:35 UTC, miello commented on apps/api/src/modules/job/job.service.spec.ts
> +import exp from 'constants'
Consider remove this, unused import

2023-02-09 13:48 UTC, miello requested changes

2023-02-09 13:48 UTC, miello commented on packages/dtos/src/job.ts
> +  @IsNotEmpty()
Is title either required or optional ?

2023-02-09 13:48 UTC, miello commented on packages/dtos/src/job.ts
> +  @IsNotEmpty()
Please consider for all properties also

2023-02-09 13:48 UTC, miello commented on packages/dtos/src/job.ts
> +  @IsNotEmpty()
Does we need to validate `ShootingDto` verify also ?

2023-02-11 08:56 UTC, PKhing requested changes
Consider these input
- minAge: -1
- actorCount: 3.5
- wage: -4235
- applicationDeadline: yesterday

2023-02-11 18:28 UTC, miello approved these changes
I will ignore these for now please fix it in `jj/back/update-job-api`

2023-02-11 18:28 UTC, miello commented on apps/api/src/modules/job/job.service.ts
> +        createJobDto.shooting[i].startDate == createJobDto.shooting[i].endDate
```suggestion
        createJobDto.shooting[i].startDate === createJobDto.shooting[i].endDate
```

2023-02-11 18:28 UTC, miello commented on apps/api/src/modules/job/job.service.spec.ts
> +        console.log(result)
Consider remove `console.log`

2023-02-11 18:51 UTC, merged