[45][50] Implement waiting page and choose signup type page
2110336-2565-2/sec2-group9-modela pull request #45
Opened 2023-02-12 14:37 UTC by miello

## What did you do

- Implement waiting page while admin verify information
- Implement choose signup type for choosing account type

## Demo

https://dev.modela.miello.dev/signup

https://dev.modela.miello.dev/waiting

![image](https://user-images.githubusercontent.com/35169079/218317235-4f6c2247-66bd-4a5c-bc7b-11c63883a625.png)

![image](https://user-images.githubusercontent.com/35169079/218317277-e2f0bc8c-ec23-4d20-a56e-f5ba5f8e40d0.png)

2023-02-13 12:08 UTC, PKhing commented
- broken responsive
- card variant should be outlined
- background-color should be darker than this?
![image](https://user-images.githubusercontent.com/19553305/218453639-7b123d42-22ca-48d8-9884-7726c0e9d369.png)

2023-02-13 12:08 UTC, PKhing commented
![image](https://user-images.githubusercontent.com/19553305/218453855-4b108a8a-592a-4e00-baa7-47b36a4f0906.png)
รูปแตก มี svg ไหมหว่า

2023-02-13 12:09 UTC, PKhing commented
should this page be at path `/` since it is the first page that user will arrive

2023-02-13 12:11 UTC, PKhing commented
![image](https://user-images.githubusercontent.com/19553305/218454414-3fc71747-a33e-4661-b087-28f262da8cd8.png)
same for this card

2023-02-13 12:12 UTC, PKhing requested changes
sorry for late review ผิดไปแล้วครับบบ

2023-02-13 12:12 UTC, PKhing commented on apps/web/src/modules/waiting/index.tsx
> +export default Waiting
should we guard this page?

2023-02-13 13:45 UTC, miello commented
> ![image](https://user-images.githubusercontent.com/19553305/218453855-4b108a8a-592a-4e00-baa7-47b36a4f0906.png) รูปแตก มี svg ไหมหว่า

ก่อนหน้านี้ผมให้ @fainrada ช่วยเช็คแล้วครับ ไม่มี svg จริง ๆ

2023-02-14 01:15 UTC, PKhing approved these changes

2023-02-14 01:20 UTC, merged