[74] Implement get all actors that applied for the specific job with jobid API
2110336-2565-2/sec2-group9-modela pull request #70
Opened 2023-02-18 08:18 UTC by PKhing

## What did you do

- Implement get all actors that applied for the specific job with jobid API with unit test
- will be edited later if frontend requires more field

## Demo

- GET /jobs/{id}/actors (I recommend you to try this on local, since we don't have any way to apply for job on dev yet)

2023-02-18 17:03 UTC, palmcm requested changes

2023-02-18 17:03 UTC, palmcm commented on apps/api/src/modules/job/application/application.service.spec.ts
> +      .map((actor) => ({ ...actor, actorId: 1, resumeId: 1 }))
should use index

2023-02-18 17:04 UTC, palmcm commented on apps/api/src/modules/job/application/application.controller.ts
> +    description: 'User is not Casting or User is not the owner of this job',
nvm if user is not casting user will not be owner anyway so "or" or "and" it doesn't matter

2023-02-18 17:24 UTC, PKhing commented on apps/api/src/modules/job/application/application.controller.ts
> +    description: 'User is not Casting or User is not the owner of this job',
I assume that UseTypeAuthGuard will throw 403 User is not Casting (should I remove type guard ?)

2023-02-18 17:25 UTC, PKhing commented on apps/api/src/modules/job/job.module.ts
> +  imports: [PrismaModule, ApplicationModule],
If I don't import nest won't see ApplicationModule (or should I import at appModule ?)

2023-02-18 17:38 UTC, palmcm commented on apps/api/src/modules/job/job.module.ts
> +  imports: [PrismaModule, ApplicationModule],
You should import it in AppModule

2023-02-18 17:44 UTC, palmcm commented on apps/api/src/modules/job/job.module.ts
> +  imports: [PrismaModule, ApplicationModule],
But If you say that ApplicationModule should be only use my JobModule you can do this.

2023-02-19 08:28 UTC, palmcm approved these changes
LGTM

2023-02-19 08:30 UTC, merged